### PR TITLE
neoneffectadded

### PR DESCRIPTION
**Pull request by NiharikaSharma18**
## Fixes Issue
i added neon effect on button

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot (73)

## Note to reviewers
now skip button looks more attarctive

### CODE REVIEW

**Comment by AyushAgnihotri2025** [comment]
Hey @NiharikaSharma18 , kindly don't spam in the repo by again and again opening the same pull again and again, and closing them immediately or closing and opening the same pull again and again.

**If you want to contribute then kindly leave it opened, I will review it and merge it, if it is fine.**

This can lead to your ban from the repo.

Hope so, you have understood 😃

**Comment by AyushAgnihotri2025** [comment]
Nice work 👍 @NiharikaSharma18, Keep It Up.

**Comment by NiharikaSharma18** [comment]
very sorry @AyushAgnihotri2025  jst trying to reslove the confict ,i did'nt know that

**Comment by AyushAgnihotri2025** [comment]
> very sorry @AyushAgnihotri2025 jst trying to reslove the confict ,i did'nt know that

No issue @NiharikaSharma18, I have resolved all of it's conflicts and also merged it too.

**Comment by NiharikaSharma18** [comment]
thank you so much sir.

**Pull request merged**
