### PR TITLE
neoneffect

### PR DESCRIPTION
**Pull request by NiharikaSharma18**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by NiharikaSharma18** [comment]
Screenshot (72)
Added neon effect on the button

**Comment by AyushAgnihotri2025** [comment]
Hey @NiharikaSharma18, your pull contains the conflicting style.css and also it's look is not much good please fix it.

image

**Comment by NiharikaSharma18** [comment]
How to resolve the conflict , sir I'm new to open source plz tell

**Comment by AyushAgnihotri2025** [comment]
Hey @NiharikaSharma18, you can reference from [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

**Pull request closed without merging**
