### PR TITLE
added a preloader to the website

### LINKED ISSUE #9: Add a preloader to the website
### Is your feature request related to a problem? Please describe.

Since the page loading time is more ,the users have to see a black screen in front of them while the page loads
to avoid this, i want to add a fascinating preloader to the website

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Janhvi52**
Closes #9 

## Changes proposed
- [✔️ ] Added a preloader to the website.

- [✔️ ] My code follows the code style of this project.
- [✔️  ] All new and existing tests passed.
- [ ✔️ ] This PR does not contain plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot (97)

Hope you like it!

### CODE REVIEW

**Comment by Janhvi52** [comment]
> Closes #9
> 
> ## Changes proposed
> * [✔️ ] Added a preloader to the website.
> * [✔️ ] My code follows the code style of this project.
> * [✔️  ] All new and existing tests passed.
> * [ ✔️ ] This PR does not contain plagiarized content.
> * [ ✔️ ] The title of my pull request is a short description of the requested changes.
> 
> ## Screenshots
> Screenshot (97)
> 

https://user-images.githubusercontent.com/97719669/208286869-a6bc563d-0533-488a-9681-44ef526e11c3.mp4


this is the actual preloader which i've added to the website
you can refer this and review my pr
> Hope you like it!

hey can you please review this and merge it @AyushAgnihotri2025

**Comment by AyushAgnihotri2025** [comment]
Hey @Janhvi52 , Nice work but I think that the background color of the preloader can be made more good looking as currently it's eye catching.

And sorry for the late review.

**Comment by Janhvi52** [comment]
> Hey @Janhvi52 , Nice work but I think that the background color of the preloader can be made more good looking as currently it's eye catching.
> 
> And sorry for the late review.

Just because the colors of your website is dynamic I thought it'll also match the requirements
but that's okay if you want me to change it? 
I'll add a preloader with a black background, that's okay to you?

**Comment by AyushAgnihotri2025** [comment]
> > Hey @Janhvi52 , Nice work but I think that the background color of the preloader can be made more good looking as currently it's eye catching.
> > And sorry for the late review.
> 
> Just because the colors of your website is dynamic I thought it'll also match the requirements but that's okay if you want me to change it? I'll add a preloader with a black background, that's okay to you?

It's ok.

**Comment by AyushAgnihotri2025** [comment]
I am accepting it @Janhvi52 btw nice work keep it up 👍 ...

**Review by AyushAgnihotri2025 — APPROVED** [review]

**Comment by Janhvi52** [comment]
> I am accepting it @Janhvi52 btw nice work keep it up 👍 ...

thanks a ton!

**Pull request merged**
